openapi: 3.0.1
info:
  title: SynchWeb OpenAPI Specification
  version: v1.0.0
servers:
  - url: 'https://localhost/api'
paths:
  /shipment/countries:
    get:
      summary: Get Countries List
      tags:
        - shipment
      description: GetList of countries for use in populating drop down list
      operationId: getShipmentCountries
      responses:
        default:
          description: Return list of contries

  /shipment/shipments/{shipmentId}:
    get:
      summary: Get Shipment
      tags:
        - shipment
      description: Get Shipment from proposal
      operationId: getShipment
      responses:
        default:
          description: Return list of proposals for the logged in user
      parameters:
        - name: shipmentId
          schema:
            type: string
          required: true
          in: path
        - $ref: '#/components/parameters/prop'
    patch:
      summary: Update Shipment
      tags:
        - shipment
      description: Update Shipment in proposal
      operationId: updateShipment
      responses:
        default:
          description: Return list of proposals for the logged in user
      parameters:
        - name: shipmentId
          schema:
            type: string
          required: true
          in: path
        - $ref: '#/components/parameters/prop'
      requestBody:
        $ref: '#/components/requestBodies/UpdateShipment'
              
  /shipment/shipments:
    get:
      summary: Get Shipments
      tags:
        - shipment
      description: Get Shipment list for proposal
      operationId: getShipments
      responses:
        default:
          description: Return list of shipments for the proposal
      parameters:
        - name: id
          schema:
            type: string
          required: false
          in: query
        - $ref: '#/components/parameters/prop'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/per_page'
    post:
      summary: Get Shipments
      tags:
        - shipment
      description: Add Shipment to proposal
      operationId: addShipments
      responses:
        default:
          description: Return list of shipments for the proposal
      requestBody:
        $ref: '#/components/requestBodies/NewShipment'

  /shipment/dewars/sid/{shipmentId}:
    get:
      summary: Get Shipments
      tags:
        - shipment
      description: Get Dewar list for shipment
      operationId: getDewarsInShipment
      responses:
        default:
          description: Return list of dewars for the dewar
      parameters:
        - name: shipmentId
          schema:
            type: string
          required: true
          in: path
        - $ref: '#/components/parameters/prop'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/per_page'

  /shipment/containers/did/{dewarId}:
    get:
      summary: Get Containers in Dewar
      tags:
        - shipment
      description: Get Container list for dewar within shipment
      operationId: getContainersInDewar
      responses:
        default:
          description: Return list of containers for the dewar
      parameters:
        - name: dewarId
          schema:
            type: string
          required: true
          in: path
        - $ref: '#/components/parameters/prop'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/per_page'

  /shipment/containers:
    post:
      summary: Add Container to Dewar
      tags:
        - shipment
      description: Add Container to dewar within shipment
      operationId: addContainerToDewar
      responses:
        default:
          description: Return container id
      requestBody:
        content:
          '*/*':
            schema:
              type: object
              properties:
                DEWARID: 
                    type: string
                new: 
                    type: string
                BARCODECHECK: 
                    type: string
                CAPACITY:
                    type: string
                CONTAINERTYPE: 
                    type: string
                NAME: 
                    type: string
                CONTAINERREGISTRYID:
                    type: string
                AUTOMATED: 
                    type: string
                BARCODE: 
                    type: string
                PERSONID: 
                    type: string
                EXPERIMENTTYPE:
                    type: string
                STORAGETEMPERATURE: 
                    type: string
                COMMENTS: 
                    type: string
                REQUESTEDIMAGERID: 
                    type: string
                SCHEDULEID: 
                    type: string
                SCREENID: 
                    type: string
                prop: 
                    type: string
  
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  parameters:
    page:
      name: page
      required: false
      in: query
      schema:
        type: integer
    per_page:
      name: per_page
      schema:
        type: integer
      required: false
      in: query
    prop:
      name: prop
      schema:
        type: string
      required: false
      in: query

  requestBodies:
    NewShipment:
      description: Request to create new Shipment
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NewShipment'
    UpdateShipment:
      description: Request to update Shipment
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BaseShipment'
  schemas:
    BaseShipment:
      properties:
        SHIPPINGNAME:
          type: string
        SAFETYLEVEL: 
          type: string
        COMMENTS: 
          type: string
        SENDINGLABCONTACTID:
          type: string
        RETURNLABCONTACTID: 
          type: string
        PHYSICALLOCATION:
          type: string
        READYBYTIME:
          type: string
        CLOSETIME: 
          type: string
        DELIVERYAGENT_SHIPPINGDATE:
          type: string
        DELIVERYAGENT_DELIVERYDATE: 
          type: string
        DELIVERYAGENT_AGENTNAME: 
          type: string
        DELIVERYAGENT_AGENTCODE: 
          type: string 
    NewShipment:
      allOf:
        - $ref: '#/components/schemas/BaseShipment'
        - type: object
          properties:
            DEWARS:
              type: string
            FCODES: 
              type: array
              items:
                type: string
            FIRSTEXPERIMENTID: 
              type: string
            noexp: 
              type: string
            SAFETYLEVEL: 
              type: string
            COMMENT: 
              type: string
    
