openapi: 3.0.1
info:
  title: SynchWeb OpenAPI Specification
  version: v0.0.0
  description: Documentation for SynchWeb REST API
servers:
  - url: 'https://localhost:8080/api'
security:
  - BearerAuth: []
paths:
  /contact:
    get:
      summary: Get lab contacts
      tags:
        - contacts
      description: Get Lab Contacts list for proposal
      operationId: getContact
      responses:
        200:
          description: The Lab Contacts
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/LabContacts'
        404:
          description: No lab contacts found for the proposal
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReponse'
      parameters:
        - $ref: '#/components/parameters/prop'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/per_page'
    post:
      summary: Create New Lab Contact
      tags:
        - contacts
      description: Create new lab contact
      operationId: addContact
      responses:
        default:
          description: >-
            Return lab contact id
      requestBody:
        $ref: '#/components/requestBodies/LabContact'
        
  /contact/{cid}:
    get:
      summary: Get lab contacts
      tags:
        - contacts
      description: Get Lab Contact information
      operationId: getContact
      responses:
        200:
          description: Lab Contact returned OK
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/LabContacts'
        404:
          description: Lab contact not found
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReponse'
      parameters:
        - name: cid
          schema:
            type: string
          required: true
          in: path
        - $ref: '#/components/parameters/prop'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/per_page'
    patch:
      summary: Update Lab Contact
      tags:
        - contacts
      description: |
        Update Lab Contact information
      operationId: updateContact
      responses:
        default:
          description: Update Lab Contact information
        404:
          description: Lab contact not found
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReponse'

      parameters:
        - name: cid
          schema:
            type: string
          required: true
          in: path
          description: Contact Id to update
  
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      
  parameters:
    page:
      name: page
      required: false
      in: query
      schema:
        type: integer
    per_page:
      name: per_page
      schema:
        type: integer
      required: false
      in: query
    prop:
      name: prop
      schema:
        type: string
      required: false
      in: query

  schemas:
    LabContact:
      title: Lab Contact Object
      type: object
      properties:
        LABCONTACTID: 
          type: integer
        CARDNAME: 
          type: string
        GIVENNAME:
          type: string
        FAMILYNAME:
          type: string
        PHONENUMBER:
          type: string
        LABNAME:
          type: string
        ADDRESS:
          type: string
        CITY:
          type: string
        COUNTRY:
          type: string
        COURIERACCOUNT:
          type: string
        BILLINGREFERENCE:
          type: string
        DEFAULTCOURRIERCOMPANY:
          type: string
        DEWARAVGCUSTOMSVALUE:
          type: integer
        DEWARAVGTRANSPORTVALUE: 
          type: integer
        EMAILADDRESS: 
          type: string
        POSTCODE:
          type: string

    LabContacts:
      type: object
      properties:
        total:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/LabContact'
          description: List of lab contact objects
          
    ErrorReponse:
      type: object
      properties:
        status: 
          type: integer
        msg: 
          type: string
  
  requestBodies:
    LabContact:
      description: A JSON object containing lab contact data
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LabContact'
            
